#ifndef PAPERBIRD_WIN32_WINDOWEXTENDEDSTYLE_H
#define PAPERBIRD_WIN32_WINDOWEXTENDEDSTYLE_H

#include <windows.h>

namespace PaperBird
{
namespace Win32
{

enum WindowExtendedStyle
{
	WindowXS_NOEXTENDEDSTYLE		= 0,
	WindowXS_DLGMODALFRAME			= WS_EX_DLGMODALFRAME,
	WindowXS_NOPARENTNOTIFY			= WS_EX_NOPARENTNOTIFY,
	WindowXS_TOPMOST				= WS_EX_TOPMOST,
	WindowXS_ACCEPTFILES			= WS_EX_ACCEPTFILES,
	WindowXS_TRANSPARENT			= WS_EX_TRANSPARENT,
#if(WINVER >= 0x0400)
	WindowXS_MDICHILD				= WS_EX_MDICHILD,
	WindowXS_TOOLWINDOW				= WS_EX_TOOLWINDOW,
	WindowXS_WINDOWEDGE				= WS_EX_WINDOWEDGE,
	WindowXS_CLIENTEDGE				= WS_EX_CLIENTEDGE,
	WindowXS_CONTEXTHELP			= WS_EX_CONTEXTHELP,
#endif /* WINVER >= 0x0400 */
#if(WINVER >= 0x0400)
	WindowXS_RIGHT					= WS_EX_RIGHT,
	WindowXS_LEFT					= WS_EX_LEFT,
	WindowXS_RTLREADING				= WS_EX_RTLREADING,
	WindowXS_LTRREADING				= WS_EX_LTRREADING,
	WindowXS_LEFTSCROLLBAR			= WS_EX_LEFTSCROLLBAR,
	WindowXS_RIGHTSCROLLBAR			= WS_EX_RIGHTSCROLLBAR,
	WindowXS_CONTROLPARENT			= WS_EX_CONTROLPARENT,
	WindowXS_STATICEDGE				= WS_EX_STATICEDGE,
	WindowXS_APPWINDOW				= WS_EX_APPWINDOW,
	WindowXS_OVERLAPPEDWINDOW		= WS_EX_OVERLAPPEDWINDOW,
	WindowXS_PALETTEWINDOW			= WS_EX_PALETTEWINDOW,
#endif /* WINVER >= 0x0400 */
#if(_WIN32_WINNT >= 0x0500)
	WindowXS_LAYERED				= WS_EX_LAYERED,
#endif /* _WIN32_WINNT >= 0x0500 */
#if(WINVER >= 0x0500)
	WindowXS_NOINHERITLAYOUT		= WS_EX_NOINHERITLAYOUT,
#endif /* WINVER >= 0x0500 */
#if(WINVER >= 0x0602)
	WindowXS_NOREDIRECTIONBITMAP	= WS_EX_NOREDIRECTIONBITMAP,
#endif /* WINVER >= 0x0602 */
#if(WINVER >= 0x0500)
	WindowXS_LAYOUTRTL				= WS_EX_LAYOUTRTL,
#endif /* WINVER >= 0x0500 */
#if(_WIN32_WINNT >= 0x0501)
	WindowXS_COMPOSITED				= WS_EX_COMPOSITED,
#endif /* _WIN32_WINNT >= 0x0501 */
#if(_WIN32_WINNT >= 0x0500)
	WindowXS_NOACTIVATE				= WS_EX_NOACTIVATE,
#endif /* _WIN32_WINNT >= 0x0500 */
};

}
}

#endif
