#ifndef PAPERBIRD_WIN32_WINDOWSTYLE_H
#define PAPERBIRD_WIN32_WINDOWSTYLE_H

#include <windows.h>

namespace PaperBird
{
namespace Win32
{

enum WindowStyle
{
	Window_OVERLAPPED		= WS_OVERLAPPED,
	Window_POPUP			= WS_POPUP,
	Window_CHILD			= WS_CHILD,
	Window_MINIMIZE			= WS_MINIMIZE,
	Window_VISIBLE			= WS_VISIBLE,
	Window_DISABLED			= WS_DISABLED,
	Window_CLIPSIBLINGS		= WS_CLIPSIBLINGS,
	Window_CLIPCHILDREN		= WS_CLIPCHILDREN,
	Window_MAXIMIZE			= WS_MAXIMIZE,
	Window_CAPTION			= WS_CAPTION,
	Window_BORDER			= WS_BORDER,
	Window_DLGFRAME			= WS_DLGFRAME,
	Window_VSCROLL			= WS_VSCROLL,
	Window_HSCROLL			= WS_HSCROLL,
	Window_SYSMENU			= WS_SYSMENU,
	Window_THICKFRAME		= WS_THICKFRAME,
	Window_GROUP			= WS_GROUP,
	Window_TABSTOP			= WS_TABSTOP,
	Window_MINIMIZEBOX		= WS_MINIMIZEBOX,
	Window_MAXIMIZEBOX		= WS_MAXIMIZEBOX,
	Window_TILED			= WS_TILED,
	Window_ICONIC			= WS_ICONIC,
	Window_SIZEBOX			= WS_SIZEBOX,
	Window_TILEDWINDOW		= WS_TILEDWINDOW,
	Window_OVERLAPPEDWINDOW	= WS_OVERLAPPEDWINDOW,
	Window_POPUPWINDOW		= WS_POPUPWINDOW,
	Window_CHILDWINDOW		= WS_CHILDWINDOW,
};

}
}

#endif
